### ISSUE TITLE
Project development plan

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/InfiniteArrays.jl#1]
Construction

- [x] Infinite ranges
- [x] Infinite diagonal
- [x] Infinite fill array
- [ ] `BandedMatrix` and `AlmostBandedMatrix`
- [ ] `RaggedMatrix`
- [x] Pretty show
- [x] Algebra arrays (`PlusInfArray`, `TimesInfArray`)
- [x] Array concatination

Linear algebra

- [ ] `mul!`
- [ ] Adjoint and transpose
- [ ] QR factorization (copy-and-paste from ApproxFun)
- [ ] LU factorization (copy-and-paste from ApproxFun)
- [ ] `ldiv!`
- [ ] `eigs`
- [ ] `expm` (scale-and-square?)

Examples

Semi-infinite:
- [ ] Taylor ODE
- [ ] Chebyshev ODE
- [ ] Wiener–Hopf factorization of Toeplitz operators

Bi-infinite:
- [ ] Finite-difference in the real line
- [ ] Waveletes

**Comment by daanhb** [comment]
Would there also be room in this package for extensions from finite arrays to (doubly) infinite sequences? It at least sounds related.

We have some code for manipulating sequences, currently in a fork of Wavelets.jl [here](https://github.com/vincentcp/Wavelets.jl/tree/master/src/sequences). The sequences are essentially doubly infinite vectors (i.e. infinite in both directions). The main use case is in signal processing, where a signal of finite length may be extended to a sequence by periodic extension, zero padding, whole- and half-point symmetric extensions, etcetera.

I guess the question is to which extent infinite arrays will hardcode starting their indices at 1, but it looks like sequences could just inherit from `InfVector` and define their own ranges. Is that so?

**Comment by dlfivefifty** [comment]
Yes. 

Since I’m copying and modifying Base code, hopefully most things will support arbitrary indices automatically.

**Comment by daanhb** [comment]
I'll just try it out, and if it results in some code reuse then I'll prepare a pull request.

**Comment by dlfivefifty** [comment]
👍 I think we can have a bunch of fun examples: wavelets, finite difference on the real line, etc.

**Comment by chakravala** [comment]
Is there any way this package could become a lighter dependency?

I'd like to use something like `InfiniteArrays` in one of my packages, but I may have to create my own custom implementation because this package makes for a too large dependency..

**Comment by dlfivefifty** [comment]
What functionality do you need? We could always split it out into InfiniteArraysBase.jl

**Comment by chakravala** [comment]
Not sure yet, I'm not very familiar with the package yet. I want to make a sparse infinite array, where the values are all usually zero, except for whatever non-zero entries were written into the array. In addition, I need a scalable `∞` symbol in my algebra, which is interpreted in various ways.

There are various ways to implement this, one way might be to use this package (although I haven't fully evaluated it for this purpose yet). However, I want the dependency to be as minimal as possible, only providing the bare necessities so that I can build it into my own algebras in various ways.

**Comment by dlfivefifty** [comment]
It sounds like what you want is for `SparseVector` to allow for `Infinity` as a length. `Infinity` could probably be moved out of this package (Infinities.jl for example) , though one would need to make a PR to fix `SparseVector`. Otherwise, you could copy the code and make your own copy of `SparseVector`

**Comment by dlfivefifty** [comment]
Closing this as most should live in InfiniteLinearAlgebra.jl
