### ISSUE TITLE
Move to JuliaArrays?

### ISSUE THREAD

**Issue by ararslan** [JuliaArrays/InfiniteArrays.jl#12]
This package seems like a good candidate to live in the JuliaArrays organization. Thoughts?

**Comment by dlfivefifty** [comment]
Yes I agree. I put it here at first since it was very experimental, though I think it’s stabilised a bit.

**Comment by dlfivefifty** [comment]
Last time I did this with LazyArrays.jl I had to transfer to an Owner of JuliaArrays. Shall I transfer to you?

(Alternatively, I could be made an owner...)

**Comment by ararslan** [comment]
I've made you an owner of JuliaArrays, so you should be able to transfer at your leisure.

**Comment by ararslan** [comment]
Seems the deed is done. 🙂
