### ISSUE TITLE
`diag(Diagonal(1:∞))` tries to cache `1:∞`

### ISSUE THREAD

**Issue by putianyi889** [JuliaArrays/InfiniteArrays.jl#147]
falls back to
https://github.com/JuliaLang/julia/blob/v1.9.4/stdlib/LinearAlgebra/src/diagonal.jl#L653-L664

**Comment by jishnub** [comment]
Perhaps in infinite cases we need to specialize `diag(D)` instead of `diag(D, k)`, as the latter may not be type-stable?

**Comment by putianyi889** [comment]
We could have both as `diag(D, k)` is better than nothing. If `D.diag` has `AbstractLazyLayout` then `diag(D)` should be `copy(D.diag)` and `diag(D, k!=0)` should be `Zeros`, and `ArrayLayouts.jl` needs to override `diag`.

Offtopic:  `copyto!(a::LazyArray.CachedArray, b)` needs to be disabled for infinite arrays as otherwise it floods the memory without warning.
