### ISSUE TITLE
`union(1:∞)` floods memory

### ISSUE THREAD

**Issue by putianyi889** [JuliaArrays/InfiniteArrays.jl#157]

**Comment by jishnub** [comment]
What's the goal here? `union` is usually expected to be called with multiple arguments, and isn't special-cased for one argument. There is a specialized `union` for two arguments in this package, but perhaps this may be generalized to multiple arguments.

**Comment by putianyi889** [comment]
at least it should throw an error.

**Comment by dlfivefifty** [comment]
> union is usually expected to be called with multiple arguments, and isn't special-cased for one argument.
That's not true:
```julia
julia> union([1,2,3,1])
3-element Vector{Int64}:
 1
 2
 3
```

**Comment by jishnub** [comment]
Yes, I meant that there's no special case like `union(x::AbstractUnitRange) = x`, and it falls back to the default implementation that allocates the result. We may special-case `union` for infinite ranges, though, since we rule out the case where the ranges don't overlap.
