### ISSUE TITLE
Sources of invalidations

### ISSUE THREAD

**Issue by pabloferz** [JuliaArrays/InfiniteArrays.jl#44]
I was analyzing sources of invalidations (maybe you are already familiar with it, but some context can be found [here](https://julialang.org/blog/2020/08/invalidations/) and [here](https://discourse.julialang.org/t/finding-and-fixing-invalidations-now-everyone-can-help-reduce-time-to-first-plot/45598)) and it seems that one of the most important is caused by this definition:

```julia
Int(::Infinity) = ∞
```

which is understandable given how it breaks a lot of the assumptions from inference in Base, where `Int(n) isa Int`, but now it can also be `::Infinity`.

I can see how eliminating that line would make supporting the whole array interface really cumbersome, but maybe it is worth trying to see if it can be restructured to improve precompilation and loading times.

**Comment by dlfivefifty** [comment]
Really I should do a PR into Base to make this hack unnecessary: I don't remember the offending code but there really isn't a good reason to convert to ` Int ` in the first place

**Comment by timholy** [comment]
All of our indexing is done with `Int`, so there's a pretty strong argument that `size` should return an `Int`.

**Comment by dlfivefifty** [comment]
It doesn't for ` BigInt(1):10 ` so that would be a breaking change to require that
