### ISSUE TITLE
Use with zip

### ISSUE THREAD

**Issue by darsnack** [JuliaArrays/InfiniteArrays.jl#67]
I'd like to be able to use this package to specify an `axes(my_custom_iter) = (InfiniteArrays.OneToInf(),)` so that I can do:
```julia
@progress for (i, j) in zip(my_custom_iter, 1:100)
  # code
end
```
The issue is that `@progress` uses `axes` to determine how long to measure progress. In this case, it is possible to objectively say that the result should be `(Base.OneTo(100),)`. Currently I get the following error:
```
ERROR: DimensionMismatch("dimensions must match: a has dims (OneToInf(),), b has dims (Base.OneTo(100),), mismatch at 1")
Stacktrace:
 [1] promote_shape(::Tuple{InfiniteArrays.OneToInf{Int64}}, ::Tuple{Base.OneTo{Int64}}) at ./indices.jl:178
 [2] _zip_promote_shape(::Tuple{InfiniteArrays.OneToInf{Int64}}, ::Tuple{Base.OneTo{Int64}}) at ./iterators.jl:320
...
```

Would it be possible to define shape promotion for `zip` in this package? It seems like we would need to intercept `Base.Iterators._promote_tuple_shape` which seems way too internal.

**Comment by dlfivefifty** [comment]
In this package I overload a lot of "too internal" methods: it is necessary to work around some issues in Base that don't properly recognise infinite arrays. Though this has improved substantially with Julia v1.6 which has now incorporated some of the support.

So I'm happy to continue overloading internal methods if you wish to make a PR.
